package org.example.utils.enums;

public enum LogsRestAssured {
    RESPONSE_ALL, RESPONSE_BODY, RESPONSE_HEADERS, RESPONSE_IFVALIDATIONFAILS, REQUEST_ALL, REQUEST_BODY, REQUEST_HEADERS, REQUEST_IFVALIDATIONFAILS, DISABLE_ALL;
}
